### ISSUE TITLE
Applying the Mitm patches for Instagram supposedly works but traffic isn't detected

### ISSUE THREAD

**Issue by wait3** [shroudedcode/apk-mitm#107]
Hi, Anyone here attempted to sniff the Instagram requests sent and received by the Instagram apk?

I went to great length to do that...newer versions of IG seems to encounter problems with apktool when rebuilding the app...but I've bypassed that using apklab and applied the fixes and rebuilt it successfully...yet it's still not showing the requests being sniffed...I've ruled out the possibility of any CA certificate misconfiguration as I can intercept other apps' requests without any issues.

I also tried older version of the Instagram APK which were successfully patched by the apk-mitm too, however unexpectedly, I wasn't able to intercept the traffic.

One other option was to use the researcher settings provided by Instagram to enable network testing mode which should in theory show the traffic in MITM without any patches...yet again no results.

So, in light of this, anyone who had a success with the Instagram app...your input would be greatly appreciated.

**Comment by marekkobida** [comment]
@wait3 Instagram Version 230.0.0.20.108 - https://github.com/itsMoji/Instagram_SSL_Pinning - happy hacking

**Comment by wait3** [comment]
@marekkobida Thanks buddy...works just fine. Much appreciated.

**Comment by marekkobida** [comment]
@wait3 you are welcome 👍
