### ISSUE TITLE
Error: Unable to access jarfile apktool_2.8.1.jar

### ISSUE THREAD

**Issue by deepindra** [shroudedcode/apk-mitm#135]
Command Used: apk-mitm --apktool apktool_2.8.1.jar base.apk

I have an error Error: Unable to access jarfile apktool_2.8.1.jar,

When I access log file, /tmp/apk-mitm-a06a97eb1e7ec1169afc6efac5782e06/logs/decoding.failed.log . It say the same.
"Error: Unable to access jarfile apktool_2.8.1.jar"

I am using debian/linux amd64. I ran command  "apk-mitm --apktool apktool_2.8.1.jar base.apk" the second time, after the first time I ran into  the issue of apktool, https://github.com/shroudedcode/apk-mitm/issues/53 but with xml error . Since the apktool was running fine with,
 java -jar apktool_2.8.1.jar 
 I thought the problem could be in apk-mitm, so I reported here.

**Comment by SashaDesigN** [comment]
make sure your jar located in same folder
Try to add ./ and additionally try absolute path to your jar. Absolute path worked for me on Mac.

**Comment by wh1ck3rd4r3** [comment]
> make sure your jar located in same folder
> Try to add ./ and additionally try absolute path to your jar. Absolute path worked for me on Mac.

This option resolves the problem! Thanks @SashaDesigN 🙏

Using:
Apk-mitm v1.2.1
Apktool v2.9.3
Uber-apk-signer v1.2.1 for .apks files!
