### ISSUE TITLE
Update Apktool

### ISSUE THREAD

**Issue by lpcs007** [shroudedcode/apk-mitm#139]
I saw that I can use a customized version of apktool. However, I would like to update the existing version of apktool in apk-mitm. Is there any command for this?

**Comment by palawer** [comment]
You can specify the your own apktool with `--apktool ~/bin/apktool_2.9.3.jar` param.

**Comment by shroudedcode** [comment]
I just updated the built-in apktool version in c9621446b86c0b37e244fb87bc20f9ba4bda0a0c and will publish a new release with it soon. Permanently changing the apktool version used by apk-mitm isn't possible right now.
