### ISSUE TITLE
Corrupted Apktool framework files cause building to fail

### ISSUE THREAD

**Issue by GamiDPC** [shroudedcode/apk-mitm#15]
Because of what could be such a mistake?

![image](https://user-images.githubusercontent.com/17031085/81213125-9abfe380-8fde-11ea-80b5-faadfd25754e.png)

**Comment by shroudedcode** [comment]
I tried reproducing your issue by downloading and patching [the same version (`2.23_81`) from APKPure](https://apkpure.com/my-world-movies-games/ru.mail.my/download/81-APK) and I didn't get any errors. Can you check whether the version you got and the one I downloaded are the same? In case they are (or at least they both produce errors), can you send me the output of running `java -version`?

**Comment by GamiDPC** [comment]
Can I contact you by telegram? To show everything?

**Comment by shroudedcode** [comment]
Sure, I'm also [@shroudedcode on Telegram](https://t.me/shroudedcode).

**Comment by shroudedcode** [comment]
After some troubleshooting through Telegram we found out that this issue was caused by Apktool's framework files being corrupted somehow. This isn't exactly a problem with `apk-mitm`, but I'm sure a workaround for it wouldn't be too difficult to implement.
