### ISSUE TITLE
 ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by Ac3n34d-X** [shroudedcode/apk-mitm#2]
Error: ENOENT: no such file or directory, open &apos;/tmp/54f37e5561c01f9cc2323574d7b732b9/decode/res/xml/network_security_config.xml
getting this erorr all the time and the directory actually opens it happens on the nextwork security config uartions stage

**Comment by shroudedcode** [comment]
It seems like the APK you were trying to patch didn't contain a `res/xml` directory, so `apk-mitm` was unable to create the `network_security_config.xml` file within it. I just released [a new version with a fix](https://github.com/shroudedcode/apk-mitm/releases/tag/v0.2.2), so please update and try again. Let me know if this has fixed your issue.
