### ISSUE TITLE
ApkTool - Version

### ISSUE THREAD

**Issue by Ac3n34d-X** [shroudedcode/apk-mitm#3]
Is it Possible to Make an Option that let's me Choose what version of apktool to be used in the process, because when I try to patch an app it shows an error in the decompilation stage, it's using the apktool 2.4.* I think, but when I use my apktool 2.3 to decompile it works perfect

**Comment by shroudedcode** [comment]
Thanks for the suggestion! I've just released [a new version](https://github.com/shroudedcode/apk-mitm/releases/tag/v0.3.0) that adds a `--apktool` option. It accepts a path to JAR file of the version you want to use. Here's an example:

```
$ apk-mitm --apktool Apktool-2.3.jar example.apk
```
