### ISSUE TITLE
apktool downloading

### ISSUE THREAD

**Issue by haythama** [shroudedcode/apk-mitm#32]
I have already apktool on my device, why to download it again?
what should I do to avoid downloading it?

**Comment by shroudedcode** [comment]
> I have already apktool on my device, why to download it again?

Because most users don't have it installed and because it gives me control over the versions of Apktool that are used with `apk-mitm` (which makes it much easier to deal with breaking changes).

> what should I do to avoid downloading it?

You can use the `--apktool` flag to use a custom Apktool JAR like so:

```
$ npx apk-mitm --apktool your-apktool.jar example.apk
```

**Comment by shroudedcode** [comment]
Closing this as the question seems to have been answered. Feel free to post another comment if that isn't the case.

**Comment by songsammy** [comment]
Maybe you should put this tip on the readme.md, as many users may have apktool installed. What's more, I am in an ISP with poor bandwidth.
