### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by forty875** [shroudedcode/apk-mitm#33]
The main code of my apk i want to inspect traffic seems to be written in javascript with webpack. I patched apk with apk-mitm but no http/https traffic will be intercepted. Seems modify AndroidManifest, injecting ssl certificate is useless here or can anybody help in this case?

`\assets\app : 
2.js
2.js.LICENSE.txt
app.js
app.js.LICENSE.txt
main.js`

**Comment by shroudedcode** [comment]
> The main code of my apk i want to inspect traffic seems to be written in javascript with webpack

Can you share the APK you're trying to patch (preferably an [APKPure](https://apkpure.com/) link)?

> no http/https traffic will be intercepted

What exactly do you mean by this? Does the app still work normally with the proxy enabled or is it showing you errors? Do you see encrypted requests or no requests at all?

**Comment by forty875** [comment]
**Sony Android TV apk:**
https://www.apkmirror.com/apk/apple-inc/apple-tv-android-tv/apple-tv-android-tv-2-1-release/apple-tv-android-tv-2-1-android-apk-download/
**Fire TV apk:**
https://www.apkmirror.com/apk/apple-inc/apple-tv-fire-tv-variant/apple-tv-fire-tv-variant-5-1-release/apple-tv-fire-tv-variant-5-1-android-apk-download/

I mean both charles or mitmproxy don't show me any requests from this app...

**Comment by shroudedcode** [comment]
I'm afraid I can't help you with this. Media apps like Apple TV usually have pretty sophisticated protections (WebSockets, non-HTTP protocols, tampering detection, more advanced certification pinning, ...) in place to prevent piracy of their video content and scraping of their metadata. `apk-mitm` was made for the 90% use case of reverse-engineering basic apps (like your average public transportation app) and was never intended to deal with these kinds of protections.

I'd recommend you to ask about this issue elsewhere.
