### ISSUE TITLE
CandyCrushSaga errors

### ISSUE THREAD

**Issue by yoshimo** [shroudedcode/apk-mitm#37]
CandyCrushSaga by King has trouble connecting to mobilecrush.king.com.
HTTPCanary claims "taget app used the non-system ca  certificate list"  even though apk-mitm patched the apk.
<TBC>

**Comment by yoshimo** [comment]
Looks like they verify against apk-mitm-8c0f4706379aecc405491c8f8b955fbc\decode\assets\res_output\ca-bundle.crt
not sure where that needs to be patched though.

**Comment by shroudedcode** [comment]
Have you searched the Smali code for that file name to see if it's read anywhere? You could also try debugging the app [like I did in your other issue](https://github.com/shroudedcode/apk-mitm/issues/34#issuecomment-770393173) (I wish I had a full guide for that, maybe I'll write it eventually :sweat_smile:).

**Comment by yoshimo** [comment]
only mentioned in the manifest and cert.sf but i  have files that contain the hostname mentioned which i will mess with next:
Debugging is a bit ouf o my league for now
```
server.host mobilecrush.king.com
server.port 443
server.secure true
server.supportsSsl true
server.page /
fb.app.id _210831918949520
adtruth.url https://play.king.com/install
mercado.url http://plataforma.sto.midasplayer.com:8008/goto/candycrush/mercado-3

servicelayer.host servicelayer.king.com
servicelayer.port 80
servicelayer.secure false
servicelayer.supportsSsl false

cmp.url https://cdn-ukwest.onetrust.com/scripttemplates/otSDKStub.js
cmp.app_id.android c484d7fd-d5e1-4f02-9e35-85341dfab524
cmp.app_id.ios 7a8f2a54-43c1-48a5-811c-8267f2728c5b
```

**Comment by yoshimo** [comment]
two changes seem to have made it work.
editing the  server.secure true  to false and merging the network security config files including the already existing domain config in addition to apk-mitm s base config.

**Comment by shroudedcode** [comment]
Thanks for looking into this yourself @yoshimo! It would be great if these changes could be applied automatically, so let's keep the issue open for now.

**Comment by shroudedcode** [comment]
Actually, it seems like this manifest is pretty specific to this one game (or maybe all games by King, but that's still pretty niche), so I don't think integrating support for patching it would be worth it. If anyone has any evidence that this file is standardized in some way (for example by being part of a major game engine), please let me know and I might reconsider adding support for it.
