### ISSUE TITLE
MVGO, mparticle sub module still pinned 

### ISSUE THREAD

**Issue by yoshimo** [shroudedcode/apk-mitm#42]
If you run APK MitM on the 1.1.0 xapk of de.mvg.mvgshare  connections to their fraud protection identity.mparticle.com  still fail due to an unknown cert.
Crawling the code right now

**Comment by shroudedcode** [comment]
Closing this because there's not much value in this issue as it stands. Feel free to post a comment if you make any progress in your investigation, then I can reopen the issue.
