### ISSUE TITLE
Support proxies

### ISSUE THREAD

**Issue by derrickberg-dev** [shroudedcode/apk-mitm#44]
Hello,

Could support be added to check for environment variables for a proxy server? I'm in an environment that requires the use of a proxy server.

Thanks

**Comment by shroudedcode** [comment]
What part of `apk-mitm` is currently not working without the proxy? The dependency downloads (Apktool and uber-apk-signer)? :thinking:

**Comment by shroudedcode** [comment]
I'm closing this issue because I have no idea what the problem is. I'll consider reopening it if someone can provide more details.
