### ISSUE TITLE
Add CLI option to automatically replace Google Maps API key with provided key

### ISSUE THREAD

**Issue by dharb** [shroudedcode/apk-mitm#45]
First of all, this is a really excellent tool you've built and I want to say thank you.

**Feature request:**
It's not always obvious that an app uses Google Maps without first using the app. This leads to some repeated work:
- patch app
- install app on device
- test patched app and discover it uses Google Maps
- uninstall app
- patch app again using `--wait` option
- replace Google Maps API key in manifest
- install app on device
- test app again

It would be great if there was a way to pass a Google Maps API key as a CLI option and automatically replace the Google Maps API key in `AndroidManifest.xml` with this key (if it exists).

**Comment by shroudedcode** [comment]
Thanks for the kind words, David! I can definitely see how this feature would be helpful, and it doesn't seem super difficult to implement. I'm pretty occupied with other projects at the moment, so I would definitely welcome a contribution for this.

Here's a couple of pointers if you or someone else decides to pick this up:

- [A new flag needs to added to `cli.ts`](https://github.com/shroudedcode/apk-mitm/blob/895fbded395c4763e6c0ea37fab4ac01ecb85204/src/cli.ts)
- The manifest has to be modified in [`modify-manifest.ts`](https://github.com/shroudedcode/apk-mitm/blob/895fbded395c4763e6c0ea37fab4ac01ecb85204/src/tasks/modify-manifest.ts)
- Inspiration can be taken from the [detection logic](https://github.com/shroudedcode/apk-mitm/blob/895fbded395c4763e6c0ea37fab4ac01ecb85204/src/tasks/modify-manifest.ts#L20) and [warning](https://github.com/shroudedcode/apk-mitm/blob/895fbded395c4763e6c0ea37fab4ac01ecb85204/src/cli.ts#L99-L101) of the App Bundle feature

I'd be happy to answer any questions!

**Comment by dharb** [comment]
Thanks for the pointers, that's super helpful. I'm happy to implement, I'll pick this up and make a PR when I get a chance (probably in the next few weeks).
