### ISSUE TITLE
Not work with dragon city game

### ISSUE THREAD

**Issue by phapntm** [shroudedcode/apk-mitm#46]
This game: https://m.apkpure.com/vn/dragon-city/es.socialpoint.DragonCity
Patched by apk-mitm but still can't capture any packet from this game.

**Comment by yoshimo** [comment]
Does the log at show any cert or TLS errors, does it occur  only for specific hosts or all of them?
That game is full of external ad components.

**Comment by phapntm** [comment]
there is nothing error while patching. 
main host: dca-p.socialpointgames.com

**Comment by phapntm** [comment]
I saw Facebook graph API request, so it already work with Facebook. 
But API from game still can't read. 
I think this APK have more class of ssl pinning

**Comment by yoshimo** [comment]
I didn't mean while patching but while running the patched apk on your device.
adb logcat can help you.

**Comment by yoshimo** [comment]
We obviously have multiple components which mention certificates

> \base-apk\decode\smali_classes3\org\cocos2dx\lib\Cocos2dxHttpURLConnection.smali 
> \base-apk\decode\smali\com\appsflyer\internal\aa.smali 
> \base-apk\decode\smali\com\google\android\gms\measurement\internal\zzkk.smali 
> \base-apk\decode\smali\okhttp3\Address.smali
> \base-apk\decode\smali_assets\audience_network\com\facebook\ads\redexgen\X\L8.smali 
> \base-apk\decode\smali_classes2\com\google\android\gms\internal\ads\zzb.smali
> \base-apk\decode\smali_classes2\com\unity3d\services\core\device\Device.smali 


apk-mitm is only mentioned in

> \base-apk\decode\smali\okhttp3\CertificatePinner.smali
> \base-apk\decode\smali_classes2\com\helpshift\websockets\OkHostnameVerifier.smali
> \base-apk\decode\smali_classes2\com\tapr\c\a\a$b.smali 
> \base-apk\decode\smali_classes2\com\tapr\c\a\a$c.smali 
> \base-apk\decode\smali_classes3\okhttp3\internal\tls\OkHostnameVerifier.smali 

Cocos and Unity look like the rigt targets although i can't find the hostname you mentioned in the strings.

**Comment by phapntm** [comment]
that hostname is  in .so file

**Comment by black-angle-cyber** [comment]
I don't Know Coding sir. But I interested in Dragon city's server. I want to know the URL Requested by Dragon City. Can you help me.

**Comment by phapntm** [comment]
they used something security so i can't see their exacly URL but i know the hostname is dca-p.socialpointgames.com
i figured out that they put all function to library "libDragonCity.so". There is no way to edit that library

**Comment by phapntm** [comment]
now. This game can't be modify anymore, they catched it up and throw an error

**Comment by shroudedcode** [comment]
Closing this as I don't want to keep app-specific issues open for too long. I'd be happy to hear about any patches that allowed you to successfully intercept the traffic's app though as it might be possible to automate them.
