### ISSUE TITLE
How to deal with system applications in odex/vdex format?

### ISSUE THREAD

**Issue by yoshimo** [shroudedcode/apk-mitm#50]
Sometimes i have applications that are shipped by the device vendor as system applications that do pinning but have no apk available.
you can adb pull the system-apps but you end up with an oat folder having a vdex and an odex file for every system application.
How do we streamline the process of pulling and patching these files and install them back on the device without wiping their user data?

**Comment by shroudedcode** [comment]
Is this something that you've done manually before or would that require an investigation as well? I'm asking because I feel like this might be out of scope for `apk-mitm` and would perhaps be better suited as a contribution to Apktool or even a separate tool altogether.

**Comment by shroudedcode** [comment]
@yoshimo I'm currently cleaning up some issues, so I'm asking again: Is this "process of pulling and patching these files" something you've done manually before and is it documented?

**Comment by shroudedcode** [comment]
Closing this due to lack of a response. I'm willing to reopen this if someone can provide a concrete proposal for how this could be implemented (or a detailed guide on how this can be done manually at the moment).
