### ISSUE TITLE
Disabling certificate pinning - Failing

### ISSUE THREAD

**Issue by DanLivassan** [shroudedcode/apk-mitm#51]
I'm trying to run the apt-mitm but i'm getting this error on Disabling certificate pinning step:
`TypeError: applicablePatches.flatMap is not a function
    at Object.processSmaliFile [as default] (/usr/local/lib/node_modules/apk-mitm/dist/tasks/smali/process-file.js:26:49)
`

**Comment by shroudedcode** [comment]
Try upgrading your Node.js version. It seems like early versions of Node.js 10 don't support that method.
