### ISSUE TITLE
Instagram latest does not work: Resource error

### ISSUE THREAD

**Issue by SplotyCode** [shroudedcode/apk-mitm#54]
Do you have any insights on how to fix this issue?

[encoding-aapt.failed.log](https://github.com/shroudedcode/apk-mitm/files/6501354/encoding-aapt.failed.log)
[encoding-aapt2.failed.log](https://github.com/shroudedcode/apk-mitm/files/6501355/encoding-aapt2.failed.log)

**Comment by shroudedcode** [comment]
This is the same issue as #53. Check out [my reply there](https://github.com/shroudedcode/apk-mitm/issues/53#issuecomment-841070925) for a couple of things you could try.
