### ISSUE TITLE
Error when try to use with airbnb.apk

### ISSUE THREAD

**Issue by danilosantana89** [shroudedcode/apk-mitm#56]
I tried to use the `apk-mitm` command with airbnb.apk and its not working.

This error shows up:

`brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_87615823857169522333744775630824863338.tmp, compile, --dir, /tmp/apk-mitm-ab6478de4c1fbd6bdc2c37ff32bfb90e/decode/res, --legacy, -o, /tmp/apk-mitm-ab6478de4c1fbd6bdc2c37ff32bfb90e/decode/build/resources.zip]`

How can i work around this?

**Comment by shroudedcode** [comment]
There should be a path to a logs directory at the end of the output. Please share all the files in there that end with `.failed.log`.

**Comment by shroudedcode** [comment]
Closing due to lack of a response.
