### ISSUE TITLE
signatures inconsistent on install

### ISSUE THREAD

**Issue by jamie7893** [shroudedcode/apk-mitm#58]
after patching a xapk i try to install it using SAI and i get this error:
"install_failed_invalid_apk: /data/app/vmdl2129945915.tmp/xxx.apk signatures are inconsistent"

**Comment by shroudedcode** [comment]
This seems to be the same issue as #55. Please comment there with more details (about your system, the app if possible, and [the resulting APK files](https://github.com/shroudedcode/apk-mitm/issues/55#issuecomment-864597604)).
