### ISSUE TITLE
Failure on installation of patched apk 

### ISSUE THREAD

**Issue by KrishnaST** [shroudedcode/apk-mitm#65]
A patched xapk giving following error on installation 

> adb install-multiple base.apk config.arm64_v8a-patched.apk

Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]

**Comment by shroudedcode** [comment]
Which version of `apk-mitm` are you using? The latest one (v1.1.0)?

**Comment by shroudedcode** [comment]
Closing this due to lack of a response.

**Comment by jacksongoode** [comment]
Having a similar issue actually.

**Comment by anktx** [comment]
@KrishnaST , I have the same error. How have you solve it?
