### ISSUE TITLE
What has gone wrong here?

### ISSUE THREAD

**Issue by rullskidan** [shroudedcode/apk-mitm#70]
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: C:\Users\home\AppData\Local\Temp\apk-mitm-cc0c9e37560ef1f5baa4a318dc9bfc63\decode\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\home\AppData\Local\Temp\brut_util_Jar_50439053876771996713683193644217495646.tmp, p, --forced-package-id, 127, --version-code, 1150075703, --version-name, 8.4.0, --no-version-vectors, -F, C:\Users\home\AppData\Local\Temp\APKTOOL10347305167167985593.tmp, -e, C:\Users\home\AppData\Local\Temp\APKTOOL9135816558176609745.tmp, -0, arsc, -I, C:\Users\home\AppData\Local\Temp\apk-mitm-cc0c9e37560ef1f5baa4a318dc9bfc63\framework\1.apk, -S, C:\Users\home\AppData\Local\Temp\apk-mitm-cc0c9e37560ef1f5baa4a318dc9bfc63\decode\res, -M, C:\Users\home\AppData\Local\Temp\apk-mitm-cc0c9e37560ef1f5baa4a318dc9bfc63\decode\AndroidManifest.xml]

  The full logs of all commands are available here:
  C:\Users\home\AppData\Local\Temp\apk-mitm-cc0c9e37560ef1f5baa4a318dc9bfc63\logs

**Comment by shroudedcode** [comment]
Please check out [this troubleshooting guide](https://github.com/shroudedcode/apk-mitm/blob/main/docs/troubleshooting/patching-fails.md) and let me know if it helps!

**Comment by shroudedcode** [comment]
Closing this due to lack of a response.
