### ISSUE TITLE
Patched app patched crashes after install

### ISSUE THREAD

**Issue by FranDisalvo90** [shroudedcode/apk-mitm#71]
Hi! I´m stuck with the following situation. I need to inspect HTTP traffic of an app. Because the app apply SSL pinning, I´m patched the app with apk-mitm tool.

After that, when I installed the APK, app crashes a seconds after. Before run apk tool the app works ok. Also, I tried to run apk-mitm with --skip-patched parameters but I had the same result. I have use apk-mitm in other cases with success.

I do not know how to debug that situation, any idea of what is going on? 

Thanks!!!

**Comment by shroudedcode** [comment]
Please take a look at the app's logs using `pidcat` and post the relevant lines here.

**Comment by FranDisalvo90** [comment]
> Please [take a look at the app's logs](https://github.com/shroudedcode/apk-mitm/blob/main/docs/troubleshooting/reading-logs.md) and post the relevant lines here.

Thanks for your answer, I could read the logs with pidcat but I´m not sure about the relevance of lines that I´m going to share. I´m compared the logs of the app working and the app that cash and there is not an error in app that crashes that does not be in the correct app.

![image](https://user-images.githubusercontent.com/5943840/135902666-c1853191-2992-4d5e-8a26-1061787fc3d5.png)
Thanks a lot!

**Comment by shroudedcode** [comment]
Sorry for the late reply Francisco, the past few weeks have been quite busy!

Regarding your logs: I also don't see any obvious lines relating to the issue you're facing, but I did notice that the app you're trying to reverse-engineer is a banking app. Something that many finance-related apps have in common is that they apply a lot of measures to enhance security (or to play [security theater](https://en.wikipedia.org/wiki/Security_theater) 😉).

It's likely that the app you're looking at contains some kind of [anti-tamper measure](https://en.wikipedia.org/wiki/Anti-tamper_software) like signature verification. Bypassing this will require you to [modify the app](https://github.com/shroudedcode/apk-mitm#making-manual-changes). Be warned that this can be quite involved as you'll have to dive into the app's Smali code. If you still want to try you can take a look at [this other issue](https://github.com/shroudedcode/apk-mitm/issues/41) where signature verification was discussed, but apart from that Google will be your friend. 😅

**Comment by FranDisalvo90** [comment]
No problem @shroudedcode! Thanks for all your advices. I'll try again with this app!!
