### ISSUE TITLE
Specify local path for ApkTool

### ISSUE THREAD

**Issue by lorenzo93** [shroudedcode/apk-mitm#81]
Hi,

It is possible to tell the app to not download ApkTool but use local version?
The app I'm trying to do MITM needs to use the beta version of ApkTool that I have locally installed.
Is there a way to do it?

**Comment by shroudedcode** [comment]
Yes, you can use the `--apktool <path-to-jar>` flag for achieving exactly that.

**Comment by lorenzo93** [comment]
It worked.

Thank you very much!
