### ISSUE TITLE
com.nbcuni.nbc

### ISSUE THREAD

**Issue by 89z** [shroudedcode/apk-mitm#82]
Using this app:

~~~
com.nbcuni.nbc
~~~

I am able to successfully patch the APK with `apk-mitm`. However the resultant APK doesnt allow for inspection. If I disable proxy, then app works as expected. If I enable proxy, I get:

~~~
Unable to Connect
Please check your internet connection and try again.
~~~

If I also install system certificate (MITM Proxy), upon starting the app, it gets stuck on initial NBC loading screen.

**Comment by 89z** [comment]
I got this working with Frida:

https://github.com/httptoolkit/frida-android-unpinning

**Comment by shroudedcode** [comment]
@89z Awesome, closing this then!

**Comment by 89z** [comment]
... I didn't post that comment as an excuse to close the issue...
