### ISSUE TITLE
Patched but failed at TLS handshake

### ISSUE THREAD

**Issue by DerLomo** [shroudedcode/apk-mitm#95]
I have a root device, the CA in the /system, and patched the APP, but the app still doesn't trust the proxy certificate:
` Client TLS handshake failed. The client may not trust the proxy's certificate for pbs.twimg.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))`
I am running this in SDK23, Android6, so I don t get why I am getting this trouble.

**Comment by nachitox** [comment]
I have the same product.
