### ISSUE TITLE
Request kotlin support

### ISSUE THREAD

**Issue by songsammy** [shroudedcode/apk-mitm#96]
I want to see how a kotlin app works, so it would be kind if you can add support for latest packages like kotlin.

**Comment by shroudedcode** [comment]
Apps written in Kotlin use the same methods for certificate pinning as apps written in Java, so there's nothing `apk-mitm` could add in that regard. If you're just interested in understanding the _code_ of an app written in Kotlin, then using [jadx](https://github.com/skylot/jadx) is probably your best bet as it will give you Java code that should at least look similar to the original Kotlin code.
